name: 🚧 Compile check

on:
  push:
    branches: [ "develop" ]
    
  pull_request:
    branches: [ "develop" ]

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔗 Checkout source code from github
      uses: actions/checkout@v3

    - name: 🛤️ Setup the build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: 🐧 Prepare the build environment
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/bootstrap.sh

    - name: 🐧 Built the application
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/build_debug.sh
      env:
        PFXCERT: ${{ secrets.PFXCERT }}
        CERTPASS: ${{ secrets.CERTPASS }}
        
    - name: ⬆️ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-build-linux-${{ github.run_id }}
        path: Release

  build-windows:
    name: Windows
    runs-on: windows-latest
    
    steps:
    - name: 🔗 Checkout source code from github
      uses: actions/checkout@v3

    - name: 🛤️ Setup the build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: 🐧 Prepare the build environment
      shell: cmd
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\bootstrap.bat

    - name: 🐧 Built the application
      shell: cmd
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\build_debug.bat

    - name: ⬆️ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-build-windows-${{ github.run_id }}
        path: Release
