name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
          
    steps:

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
                 
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies
      run: dotnet restore "Carbon.Core"
      
    - name: Restore Packages
      run: dotnet restore "Carbon.Core" --force
      
    - name: Build
      run: msbuild "Carbon.Core" -t:restore -p:RestorePackagesConfig=true /p:Configuration=Release
