name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
          
    steps:
    
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: "Carbon.Core1.0.0.zip"
        bodyFile: "body.md"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
                 
    - uses: actions/checkout@v3
      
    - name: Build
      run: msbuild "Carbon.Core" -t:restore -p:RestorePackagesConfig=true /p:Configuration=Release
