###
### Copyright (c) 2022 Carbon Community 
### All rights reserved
###
name: Production Build
concurrency: build-1-production

on:
  schedule:
    - cron: '30 18 * * 4'
    
  push:
    branches:
      - production

  workflow_dispatch:

jobs:
  bootstrap:
    name: 🥾 Bootstrap
    runs-on: ubuntu-latest

    outputs:
      date:  ${{ steps.step1.outputs.date }}
      clock: ${{ steps.step1.outputs.clock }}
      tag:   ${{ steps.step1.outputs.tag }}
      ref:   ${{ steps.step1.outputs.ref }}
      wipe:  ${{ steps.step1.outputs.wipe }}

    steps:
      #- name: 🪵 Log environment
      #  uses: crazy-max/ghaction-dump-context@v1

      - name: 🔗 Checkout source code from github
        uses: actions/checkout@v3
        with:
          ref: production

      - name: 📅 Prepare the environment
        id: step1
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "clock=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "tag=$(date +'%Yd%j')" >> $GITHUB_OUTPUT
          echo "ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "wipe=$( [ $(date +%u) -eq 4 ] && [ $(date +%d) -le 7 ] && echo true || echo false )" >> $GITHUB_OUTPUT

  build-linux:
    name: 🐧 Linux
    needs: bootstrap
    runs-on: ubuntu-latest
    continue-on-error: false

    outputs:
      wipe: ${{ needs.bootstrap.outputs.wipe }}
      artifact: build-production-${{ needs.bootstrap.outputs.ref }}-linux
      build_info: Built at ${{ needs.bootstrap.outputs.date }} ${{ needs.bootstrap.outputs.clock }} based on commit ${{ needs.bootstrap.outputs.ref }}.
    
    steps:
    - name: 🔗 Checkout source code from github
      uses: actions/checkout@v3
      with:
        ref: production

    - name: 🛤️ Setup the dotnet build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: 🪚 Setup the Carbon build environment
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/bootstrap.sh

    - name: 🐧 Built Carbon on Linux
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/build.sh ReleaseUnix
        
    - name: ⬆️ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-production-linux
        path: |
          Release/Carbon.ReleaseUnix.tar.gz
          Release/build-unix.info

  build-windows:
    name: 🪟 Windows
    needs: bootstrap
    runs-on: windows-latest
    continue-on-error: false
    
    steps:
    - name: 🔗 Checkout source code from github
      uses: actions/checkout@v3
      with:
        ref: production

    - name: 🛤️ Setup the dotnet build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: 🪚 Setup the Carbon build environment
      shell: cmd
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\bootstrap.bat

    - name: 🪟 Built Carbon on Windows
      shell: cmd
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\build.bat Release

    - name: ⬆️ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-production-windows
        path: |
          Release/Carbon.Release.zip
          Release/build.info

  release:
    name: 💾 Release
    needs: [ "build-linux", "build-windows" ]
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule' && needs.build-linux.outputs.wipe == 'true') }}

    steps:
    - name: ⬇️ Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: Release/
        
    - name: 🗑️ Delete existing release tag
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: production_build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 🏷️ Update release tag
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        tag_name: production_build
        name: 'Carbon Build (production)'
        body: |
          This is a release build of Carbon based on the `production` branch.
          This build is targeted at the general public.

          ### How to install
          1. Download the `Carbon.Release[Unix].zip` archive from the attachments below.
          2. Unzip the archive to the root of your Rust Dedicated Server.
          3. Restart the server and enjoy.
          
          ${{ needs.build-linux.outputs.build_info }}
        files: |
          Release/build-production-windows/Carbon.Release.zip
          Release/build-production-linux/Carbon.ReleaseUnix.tar.gz
          Release/build-production-linux/build-unix.info
          Release/build-production-windows/build.info
